dist: xenial
language: java

cache:
  directories:
    - $HOME/.local
    - bucket

install:
  - java --version
  - pip install --user awscli
  - export PATH=$PATH:$HOME/.local/bin
  - aws --version

script:
  - mkdir --parents bucket
  - du --bytes bucket
  - aws s3 sync s3://java9plusadoption bucket --region us-east-1 --no-sign-request
  - du --bytes bucket
  - java src/Modules.java bucket
