dist: xenial
language: java

env:
  global:
    secure: "UzDSPvvCq6PfzxbF1TQlIAKgZEdGT/8zjoLeL7GbtxopuOMIUVhRWEDiiHpfbdd19JUmM0HhAg1yOpU/3gNhR22yZHeqRtwJ3IMBSfPy8Ek2V+3p/3k0/huiSKxS08jqqTFSTaLVCppbi+7wj+Ak++2BKAhx2EFL5NUO8iEn6mg4lg++PZL6Saji8lLXRK03wXNpES/UYTwCiKfObA/Ncnn0GZYJFCq0DDHHO1ADgEBDGAI+0l3EfblQeNNfP7nIDGQs02WKkdwr6bn8S3XMHKaii1oRMXKWOq1NNylWz8BcfSu5yF29ZjTQUNNY0jG7N+xtsRZNzih+AQGRynaKF9SDSSwD2pgr5FwhBT32VrxMwJXFX3G2XNC7dQqDEQxr1IFE4gCQ9yrmRqXkwGAjiovw+svfEpSPSsELso65AghdDPIahkFQMDvl3U1lr8RUvl7+tBmXqf6zl1YXkrBV3RPFzNPhdT3j2vCCRCDzy86nZRxAb8LYsth4mGXecxbfNkMZdc1j1oMdrSDor5x65IFcTZUSKTQ/az8MeiQuPh6GwGs4HDp3SbxKpkTQLaXgpn7FZUVGvhl3pv2v3nXxwUgoeCg2IGxZb8U4wpCIWX7GROlcFfGbt1AfjuPxDBHdug91Kmv1PMTHxPS94bW/1WcEVeF1Fy3t0Hdwz6mEZXM="

cache:
  directories:
    - $HOME/.local
    - bucket

install:
  - java --version
  - pip install --user awscli
  - export PATH=$PATH:$HOME/.local/bin
  - aws --version

script:
  - mkdir --parents bucket
  - du --bytes bucket
  - aws s3 sync s3://java9plusadoption bucket --region us-east-1 --no-sign-request
  - du --bytes bucket
  - java src/Modules.java bucket

after_success:
  - git status
  - git commit --message "[skip ci] Update modules (${TRAVIS_BUILD_NUMBER})"
  - git status
  - git push --dry-run
